# Comandos
# https://duducp.github.io/susa/guides/adding-commands/

name: "ASDF"
description: "Mostra a vers√£o do Susa CLI"
entrypoint: "main.sh"
sudo: false
group: "text"  # opcional
os: ["linux", "mac"]
envs:
  ENABLED: true
